name: Ping
version: 1.0.0
main: Ping\main
api: 3.0.0
description: Plugin that can show your ping by using /ping.
author: Dready
commands:
  ping:
    description: Show your or another player's ping!
